x-common-env: &common-env
  TZ: America/Sao_Paulo

services:

  postgres:
    image: postgres:15
    container_name: mlflow-postgres

    environment:
      <<: *common-env
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d

    ports:
      - "5432:5432"

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"
        ]
      interval: 5s
      timeout: 3s
      retries: 10

    networks:
      mlflow-network:
        ipv4_address: 172.25.0.2

  minio:
    image: minio/minio:latest
    container_name: mlflow-minio

    command: server /data --console-address ":9001"

    environment:
      <<: *common-env
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}

    volumes:
      - ./minio-data:/data

    ports:
      - "9000:9000"
      - "9001:9001"

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -fsS http://localhost:9000/minio/health/live || exit 1"
        ]
      interval: 5s
      timeout: 3s
      retries: 20

    networks:
      mlflow-network:
        ipv4_address: 172.25.0.3

  create-bucket:
    image: minio/mc:latest
    container_name: mlflow-create-bucket

    depends_on:
      minio:
        condition: service_healthy

    restart: "no"

    entrypoint:
      - /bin/sh
      - -c
      - |
        mc alias set myminio http://minio:9000 \
          ${MINIO_ROOT_USER} \
          ${MINIO_ROOT_PASSWORD}

        mc mb --ignore-existing myminio/${MINIO_BUCKET}

        mc anonymous set private myminio/${MINIO_BUCKET}

    environment:
      <<: *common-env
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_BUCKET: ${MINIO_BUCKET}

    networks:
      mlflow-network:
        ipv4_address: 172.25.0.4

  mlflow:
    build:
      context: .
      dockerfile: scripts/mlflow.Dockerfile

    container_name: mlflow-server

    depends_on:
      postgres:
        condition: service_healthy

      create-bucket:
        condition: service_completed_successfully

    environment:
      <<: *common-env

      MLFLOW_BACKEND_STORE_URI: ${MLFLOW_BACKEND_STORE_URI}
      MLFLOW_ARTIFACTS_DESTINATION: ${MLFLOW_ARTIFACTS_DESTINATION}

      AWS_ACCESS_KEY_ID: ${MINIO_ROOT_USER}
      AWS_SECRET_ACCESS_KEY: ${MINIO_ROOT_PASSWORD}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}

      MLFLOW_S3_ENDPOINT_URL: ${MLFLOW_S3_ENDPOINT_URL}

      MINIO_BUCKET: ${MINIO_BUCKET}

    ports:
      - "5000:5000"

    healthcheck:
      test:
        [
          "CMD",
          "python",
          "-c",
          "import urllib.request; urllib.request.urlopen('http://localhost:5000')"
        ]
      interval: 10s
      timeout: 5s
      retries: 30

    restart: unless-stopped

    networks:
      mlflow-network:
        ipv4_address: 172.25.0.5


  redis:
    image: redis:7
    container_name: superset_redis
    restart: always
    environment:
      <<: *common-env
    expose:
      - "6379"
    networks:
      mlflow-network:
        ipv4_address: 172.25.0.6

  superset:
    build:
      context: scripts
      dockerfile: superset.Dockerfile

    container_name: superset
    restart: always
    depends_on:
      - postgres
      - redis
    ports:
      - "8088:8088"
    volumes:
      - ./scripts/superset_config.py:/app/superset_config.py
    environment:
     <<: *common-env
    networks:
      mlflow-network:
        ipv4_address: 172.25.0.7


  superset-worker:
    build:
      context: scripts
      dockerfile: superset.Dockerfile
    container_name: superset_worker
    restart: always
    depends_on:
      - redis
      - postgres
    command: celery --app=superset.tasks.celery_app:app worker --loglevel=INFO
    environment:
      <<: *common-env
    networks:
      mlflow-network:
        ipv4_address: 172.25.0.8

  superset-beat:
    build:
      context: scripts
      dockerfile: superset.Dockerfile
    container_name: superset_beat
    restart: always
    environment:
      <<: *common-env
    depends_on:
      - redis
      - postgres
    command: celery --app=superset.tasks.celery_app:app beat --loglevel=INFO
    networks:
      mlflow-network:
        ipv4_address: 172.25.0.9



networks:
  mlflow-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/16